{% set name = "diffutils" %}
{% set version = "3.7" %}
{% set sha256 = "b3a7a6221c3dc916085f0d205abf6b8e1ba443d4dd965118da364a1dc1cb3a26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libiconv

test:
  commands:
    - cmp --version
    - diff --version
    - diff3 --version
    - sdiff --version

about:
  home: https://www.gnu.org/software/diffutils/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GNU Diffutils is a package of several programs related to finding differences between files.

  doc_url: https://www.gnu.org/software/diffutils/manual/html_node/index.html
  dev_url: http://git.savannah.gnu.org/cgit/diffutils.git

extra:
  recipe-maintainers:
    - bgruening
    - beatrizserrano
    - davelopez
